blockchain:
  - blockchain/**

proto:
  - blockchain/proto/wardenprotocol/**

treasury:
  - blockchain/x/treasury/**
  - blockchain/proto/wardenprotocol/treasury/**

identity:
  - blockchain/x/identity/**
  - blockchain/proto/wardenprotocol/identity/**

intent:
  - blockchain/x/intent/**
  - blockchain/proto/wardenprotocol/intent/**

test:
  - '**/*_test.go'

docs:
  - docs/**

go-client:
  - go-client/**

keychain:
  - keychain/**

relayer-eth:
  - relayer-eth/**

web:
  - web/**
