version: "3"

services:
  wardendnode0:
    container_name: wardendnode0
    image: "wardend/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-wardend.log}
    volumes:
      - ./localnet-setup/node0/wardend:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  wardendnode1:
    container_name: wardendnode1
    image: "wardend/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-wardend.log}
    volumes:
      - ./localnet-setup/node1/wardend:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  wardendnode2:
    container_name: wardendnode2
    image: "wardend/node"
    environment:
      - ID=2
      - LOG=${LOG:-wardend.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/wardend:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  wardendnode3:
    container_name: wardendnode3
    image: "wardend/node"
    environment:
      - ID=3
      - LOG=${LOG:-wardend.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/wardend:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
