name: test
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  unit-test:
    name: test
    defaults:
      run:
        working-directory: ./${{ inputs.path }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: "**/*.sum"
      - name: Build
        run: go build -v ./...
      - name: Test (-race)
        run: go test -race -v ./...
